# Alembic Configuration File
# For Alembic documentation and examples, see https://alembic.sqlalchemy.org/

[sqlalchemy]
# the sqlalchemy connection string. This setting is looked up at runtime
# using the get_main_option() method; this mechanism permits the configuration
# to load a sqlalchemy connection string from a file or environment variable
sqlalchemy.url = sqlite:///./data/tournament.db

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the constructor of datetime.datetime
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# set to 40 to truncate and generate unique
# names, using a prefix [n] for added dups
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be treated as revisions in the
# versions/ directory
# sourceless = false

# When set to 'true', this option activates the environment variable parsing
# feature where a percent sign-prefixed environment variable name is expanded.
# The variables are included via the sqlalchemy.url configuration variable.
# When multiple environment variables were specified, they are joined as a
# single database URL. support.sqlalchemy_url_expansion is deprecated as of
# Alembic 1.18 in favor of the environment_from environment variable. However,
# this variable is still used if sqlalchemy_url_expansion is set to true.
# support.sqlalchemy_url_expansion = true

# set the location of the env.py callback script
# env_script_location = %(here)s

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S


