"""
Voice Command Calibration — Pure domain package.

Provides models, state machine, alias policy, and service logic
for measuring ASR accuracy and command recognition quality without
mutating scores or depending on Streamlit/WebRTC/ASR providers.
"""

from tournament_platform.app.services.voice_calibration.models import (
    AcousticCaptureContext,
    AcousticCaptureSummary,
    AcousticMeasurementResult,
    AcousticSummarySnapshot,
    AcousticRecommendation,
    AcousticRecommendationCode,
    AliasCandidateStatus,
    AliasConfirmationCandidate,
    AsrAbSampleResult,
    AsrAbWorkItem,
    AsrExperimentAggregate,
    AsrExperimentConfig,
    AsrExperimentRecommendation,
    AsrExperimentStatus,
    AsrExperimentTranscript,
    AsrProviderCapabilities,
    AsrMetadata,
    CalibrationAliasCandidate,
    CalibrationCaptureKind,
    CalibrationMeasurementKind,
    CalibrationOverallStatus,
    CalibrationPhase,
    CalibrationProfileIdentity,
    CalibrationProfileStatus,
    CalibrationProfileStore,
    CalibrationSectionOutcome,
    CalibrationSession,
    CalibrationState,
    CalibrationConfusionEntry,
    CalibrationResults,
    CalibrationSafetyOutcome,
    CalibrationVerdictReason,
    CommandCalibrationResult,
    CommandPhraseCandidate,
    CommandRecognitionEntry,
    CommandTrial,
    Collision,
    ExperimentIdentity,
    LiveVoiceProfileRecommendation,
    LiveVoiceRuntimeConfig,
    LiveVoiceSettingsSnapshot,
    NegativeSpeechSnapshot,
    NegativeTrial,
    NegativeTrialClassification,
    NoiseGateRecommendation,
    NoiseGateRecommendationPolicy,
    ParserCandidateInfo,
    PhraseComparisonResult,
    RecommendationEvidence,
    RecommendationStatus,
    SilenceBaselineMetrics,
    SpeechLevelMetrics,
    TtsEchoSnapshot,
    TtsEchoTestContext,
    TtsEchoTranscript,
    TtsEchoTranscriptInfo,
    TrialClassification,
    ValidationResult,
    VerificationMetadata,
    VoiceCalibrationProfile,
    VoiceProfileActivationStatus,
)
from tournament_platform.app.services.voice_calibration.alias_policy import (
    CalibrationAliasPolicy,
)
from tournament_platform.app.services.voice_calibration.service import (
    VoiceCalibrationService,
)
from tournament_platform.app.services.voice_calibration.asr_ab_worker import (
    AsrAbWorker,
)
from tournament_platform.app.services.voice_calibration.profile_store import (
    InMemoryCalibrationProfileStore,
)
from tournament_platform.app.services.voice_calibration.state_machine import (
    CalibrationPhaseMachine,
)


__all__ = [
    "AcousticCaptureContext",
    "AcousticCaptureSummary",
    "AcousticMeasurementResult",
    "AcousticSummarySnapshot",
    "AcousticRecommendation",
    "AcousticRecommendationCode",
    "AliasCandidateStatus",
    "AliasConfirmationCandidate",
    "AsrAbSampleResult",
    "AsrAbWorkItem",
    "AsrAbWorker",
    "AsrExperimentAggregate",
    "AsrExperimentConfig",
    "AsrExperimentRecommendation",
    "AsrExperimentStatus",
    "AsrExperimentTranscript",
    "AsrProviderCapabilities",
    "AsrMetadata",
    "CalibrationAliasCandidate",
    "CalibrationCaptureKind",
    "CalibrationMeasurementKind",
    "CalibrationOverallStatus",
    "CalibrationPhase",
    "CalibrationPhaseMachine",
    "CalibrationProfileIdentity",
    "CalibrationProfileStatus",
    "CalibrationProfileStore",
    "CalibrationSectionOutcome",
    "CalibrationSession",
    "CalibrationState",
    "CalibrationAliasPolicy",
    "CalibrationConfusionEntry",
    "CalibrationResults",
    "CalibrationSafetyOutcome",
    "CalibrationVerdictReason",
    "CommandCalibrationResult",
    "CommandPhraseCandidate",
    "CommandRecognitionEntry",
    "CommandTrial",
    "Collision",
    "ExperimentIdentity",
    "InMemoryCalibrationProfileStore",
    "LiveVoiceProfileRecommendation",
    "LiveVoiceRuntimeConfig",
    "LiveVoiceSettingsSnapshot",
    "NegativeSpeechSnapshot",
    "NegativeTrial",
    "NegativeTrialClassification",
    "NoiseGateRecommendation",
    "NoiseGateRecommendationPolicy",
    "ParserCandidateInfo",
    "PhraseComparisonResult",
    "RecommendationEvidence",
    "RecommendationStatus",
    "SilenceBaselineMetrics",
    "SpeechLevelMetrics",
    "TtsEchoSnapshot",
    "TtsEchoTestContext",
    "TtsEchoTranscript",
    "TtsEchoTranscriptInfo",
    "TrialClassification",
    "ValidationResult",
    "VerificationMetadata",
    "VoiceCalibrationProfile",
    "VoiceCalibrationService",
    "VoiceProfileActivationStatus",
]
